import { MenuItem, SupperClubEvent, VinylTrack } from './types';

export const PROVISIONS_MENU: MenuItem[] = [
  // Small Plates
  {
    id: 'm1',
    name: 'Cast-Iron Skillet Cornbread',
    price: 18,
    description: 'Fresh-milled heirloom corn meal, baked in smoking cast iron. Finished with whipped lavender honey-butter and hand-harvested smoked flake sea salt.',
    course: 'Small Plates',
    dietary: ['Vegetarian'],
    ingredients: ['Heirloom Cornmeal', 'Lavender Butter', 'Raw South LA Honey', 'Maldon Salt'],
    highlighted: true,
  },
  {
    id: 'm2',
    name: 'Crispy Georgia Peach Barbecue Belly',
    price: 24,
    description: 'Slow-confit heritage pork belly crisped skin-down, glazed in a reduced View Park peach nectar and house mustard bbq. Served over a purée of local collar greens.',
    course: 'Small Plates',
    ingredients: ['Heritage Pork Belly', 'Peach Barbecue Glaze', 'Mustard Greens', 'Pickled Mustard Seeds'],
    highlighted: false,
  },
  {
    id: 'm3',
    name: 'Carolina Crab Beignets',
    price: 26,
    description: 'Pillow-soft savory fritters loaded with fresh sweet blue lump crab, folded with chives. Served with a warm Cajun-spiced brown-butter remoulade.',
    course: 'Small Plates',
    ingredients: ['Blue Lump Crab', 'Chives', 'Brown-Butter Remoulade', 'Lemon Confit'],
    highlighted: true,
  },
  {
    id: 'm4',
    name: 'Blistered Baldwin Hills Okra',
    price: 19,
    description: 'Young okra charred on the stone grill, tossed in hand-pressed smoked paprika oil, toasted benne seeds, and whipped garlic yogurt.',
    course: 'Small Plates',
    dietary: ['Vegetarian', 'Gluten-Free'],
    ingredients: ['Blistered Okra', 'Smoked Paprika Oil', 'Toasted Benne Seeds', 'Garlic Yogurt'],
    highlighted: false,
  },

  // Mains
  {
    id: 'm5',
    name: '24-Hour Pot-Liquor Braised Short Rib',
    price: 54,
    description: 'Grass-fed prime beef short rib simmered in smoked turkey pot-liquor. Rested over stone-ground white heirloom grits, finished with micro-mustard greens and natural reduction.',
    course: 'Mains',
    dietary: ['Gluten-Free'],
    ingredients: ['Prime Short Rib', 'Stone-Ground Grits', 'Rich Pot-Liquor Jus', 'Micro Greens'],
    highlighted: true,
  },
  {
    id: 'm6',
    name: 'Golden Cast-Iron Heritage Half-Chicken',
    price: 46,
    description: 'Brined in organic sweet tea, slow-charred inside-out. Plated atop velvet sweet potato cream, hand-massaged wilted Southern collards, and a splash of bourbon-pecan reduction.',
    course: 'Mains',
    ingredients: ['Sweet Tea Half-Chicken', 'Sweet Potato Purée', 'Southern Collards', 'Bourbon Pecan Glaze'],
    highlighted: false,
  },
  {
    id: 'm7',
    name: 'Seared Red Snapper & Crawfish Roux',
    price: 52,
    description: 'Wild-caught Pacific Red Snapper skin-seared to a crisp, over a bed of legacy Carolina Gold rice. Drenched in a crawfish and sweet-pepper heritage gumbo reduction.',
    course: 'Mains',
    ingredients: ['Pacifc Snapper', 'Carolina Gold Rice', 'Crawfish Gumbo Roux', 'Wilted Okra Rings'],
    highlighted: true,
  },
  {
    id: 'm8',
    name: 'Smoked King Oyster Mushrooms & Succotash',
    price: 42,
    description: 'Thick hardwood-smoked oyster mushrooms basted with herb reduction, over a rich summer sweet-corn, edamame, and lima bean succotash in savory pecan milk.',
    course: 'Mains',
    dietary: ['Vegan', 'Gluten-Free'],
    ingredients: ['King Oyster Mushrooms', 'Sweet Corn Succotash', 'Creamy Pecan Milk', 'Pomegranate Arils'],
    highlighted: false,
  },

  // Final Notes
  {
    id: 'm9',
    name: 'Skillet Smoked Peach Cobbler',
    price: 18,
    description: 'Macerated organic fire-roasted peaches baked beneath a cracked Demerara sugar biscuit. Served with a generous quenelle of cold house-made Madagascar vanilla bean chantilly.',
    course: 'Final Notes',
    dietary: ['Vegetarian'],
    ingredients: ['Roasted Peaches', 'Demerara Biscuit Crust', 'Bourbon Caramel', 'Madagascar Chantilly'],
    highlighted: true,
  },
  {
    id: 'm10',
    name: 'Sweet Potato Velvet Panna Cotta',
    price: 18,
    description: 'A decadent and silky southern-spiced panna cotta layer, topped with crunchy praline-candied pecans, scorched marshmallow meringue, and high-end scotch whiskey syrup.',
    course: 'Final Notes',
    dietary: ['Gluten-Free'],
    ingredients: ['Sweet Potato Custard', 'Praline Pecans', 'Marshmallow Meringue', 'Scotch Syrup'],
    highlighted: false,
  },
  {
    id: 'm11',
    name: 'Red Velvet Dark Ganache Tart',
    price: 19,
    description: 'Deep buttermilk cocoa dough crust, loaded with a 72% dark Valrhona chocolate ganache, micro beet dust, and layered hints of cream cheese frosting. Adorned with edible 24k gold leaf flakes.',
    course: 'Final Notes',
    dietary: ['Vegetarian'],
    ingredients: ['Cocoa Tart Custard', 'Valrhona Chocolate', 'Cream Cheese Curds', '24k Gold Flakes'],
    highlighted: true,
  },
];

export const EVENTS: SupperClubEvent[] = [
  {
    id: 'ev-1',
    title: 'Heritage & Hearth: View Park Twilight',
    date: 'Friday, June 12, 2026',
    time: '6:30 PM — 10:00 PM',
    price: 145,
    capacity: 24,
    ticketsLeft: 4,
    neighborhood: 'View Park',
    locationDetail: 'An architectural mid-century indoor-outdoor modern residential estate high above the city.',
    curatedVinylSummary: 'Summer-themed rare groove, 1970s jazz funk, and vintage Philadelphia soul vinyl records spun on high-fidelity tube amps.',
    curatedVinylPlaylistId: 'track-1',
    status: 'Selling Fast',
    atmosphere: 'Intimate seating surrounding the central stone outdoor hearth under California palms.',
  },
  {
    id: 'ev-2',
    title: 'Solstice Sound & Soul: Baldwin Hills Oasis',
    date: 'Saturday, June 20, 2026',
    time: '7:00 PM — 10:30 PM',
    price: 160,
    capacity: 30,
    ticketsLeft: 12,
    neighborhood: 'Baldwin Hills',
    locationDetail: 'An expansive private terrace hillside garden overlooking the magnificent downtown skyline.',
    curatedVinylSummary: 'A curated dialogue between Roy Ayers, Kool & The Gang, and deep spiritual jazz fusion records.',
    curatedVinylPlaylistId: 'track-2',
    status: 'Open',
    atmosphere: 'Staggered wooden communal bench boards draped in custom linens with ambient soft terracotta uplighting.',
  },
  {
    id: 'ev-3',
    title: 'The Ancestral Table: Leimert Park Parlor',
    date: 'Saturday, June 27, 2026',
    time: '6:00 PM — 9:30 PM',
    price: 150,
    capacity: 18,
    ticketsLeft: 1,
    neighborhood: 'Leimert Park',
    locationDetail: 'An executive historic parlor space surrounded by original Black art and a beautiful wall-to-wall record library.',
    curatedVinylSummary: 'Classic analog recordings of Minnie Riperton and Outkast, celebrating warmth, soul, and vocal mastery.',
    curatedVinylPlaylistId: 'track-4',
    status: 'Selling Fast',
    atmosphere: 'Extremely personal indoor dynamic seating. The chef cooks and discusses every plate live in front of you.',
  },
  {
    id: 'ev-4',
    title: 'Ember, Air & Soul: Ladera Heights Lawn',
    date: 'Friday, July 04, 2026',
    time: '6:30 PM — 10:00 PM',
    price: 155,
    capacity: 40,
    ticketsLeft: 40,
    neighborhood: 'Ladera Heights',
    locationDetail: 'A manicured botanical lawn behind an elegant gated mid-century modern private compound.',
    curatedVinylSummary: 'Vibrant, high-tempo funk, classic brass ensembles, and sweet golden soul grooves.',
    curatedVinylPlaylistId: 'track-3',
    status: 'Open',
    atmosphere: 'Open-air long-table dining under a constellation of glowing bulb garlands and roaring fireplace smoke.',
  },
];

export const VINYL_PLAYLIST: VinylTrack[] = [
  {
    id: 'track-1',
    title: 'Everybody Loves the Sunshine',
    artist: 'Roy Ayers Ubiquity',
    album: 'Vibrations',
    releaseYear: 1976,
    albumCover: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
    moodTag: 'Vibrant Summer Twilight',
    labelColor: '#C86A4B',
    vibes: ['Golden-hour warmth', 'Vibraphone bliss', 'South LA breeze'],
  },
  {
    id: 'track-2',
    title: 'Summer Madness',
    artist: 'Kool & The Gang',
    album: 'Light of Worlds',
    releaseYear: 1974,
    albumCover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80',
    moodTag: 'Night Solitude Breeze',
    labelColor: '#D4AF37',
    vibes: ['Ambient synth soaring', 'Slow jazz-funk ride', 'Understated elegance'],
  },
  {
    id: 'track-3',
    title: 'Prototype',
    artist: 'Outkast',
    album: 'The Love Below',
    releaseYear: 2003,
    albumCover: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=400&q=80',
    moodTag: 'Neo-Soul Warmth',
    labelColor: '#3B82F6',
    vibes: ['Elden falsettos', 'Lush electric guitar layers', 'Romantic starlight'],
  },
  {
    id: 'track-4',
    title: 'Inside My Love',
    artist: 'Minnie Riperton',
    album: 'Adventures in Paradise',
    releaseYear: 1975,
    albumCover: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=400&q=80',
    moodTag: 'Intimate Candlelight',
    labelColor: '#E11D48',
    vibes: ['Legendary whistle notes', 'Vampy analog strings', 'Sensual hearth glow'],
  },
  {
    id: 'track-5',
    title: 'We Live in Brooklyn, Baby',
    artist: 'Roy Ayers',
    album: 'He Coming',
    releaseYear: 1972,
    albumCover: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80',
    moodTag: 'Classic Gritty Soul-Jazz',
    labelColor: '#8B5CF6',
    vibes: ['Hypnotic bass melody', 'Vintage organ resonance', 'Sizzling hi-hats'],
  },
];
